version: '3'

services:
  hydra-migrate:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10
    links:
      - postgresd:postgresd
    networks:
      - intranet
    environment:
      - LOG_LEVEL=debug
      - SYSTEM_SECRET=youreallyneedtochangethis
    command:
      migrate sql postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
    restart: on-failure

  keto-migrate:
    image: oryd/keto:v0.2.2-sandbox_oryOS.10
    links:
      - postgresd
    environment:
      - LOG_LEVEL=debug
    networks:
      - intranet
    command:
      migrate sql postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
    restart: on-failure

  oathkeeper-migrate:
    image: oryd/oathkeeper:v0.14.2_oryOS.10
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
    networks:
      - intranet
    command:
      migrate sql postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
    restart: on-failure

  hydra_admin:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10
    container_name: hydra_admin
    networks:
      - intranet
      - web
    command: serve admin --dangerous-force-http
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
      - SYSTEM_SECRET=youreallyneedtochangethis
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hydra_admin"
      - "traefik.frontend.rule=Host:admin.${DOMAIN_NAME}"
      - "traefik.port=4445"
      - "traefik.docker.network=web"
    restart: on-failure
    ports:
      - "4445:4445"
    volumes:
      - "./config/:/config/"

  hydra_public:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10
    container_name: hydra_public
    networks:
      - intranet
      - web
    command: serve public --dangerous-force-http
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
      - OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - OAUTH2_LOGIN_URL=http://localhost:3000/login
      - SYSTEM_SECRET=youreallyneedtochangethis
      - OAUTH2_ISSUER_URL=http://api.${DOMAIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hydra_api"
      - "traefik.frontend.rule=Host:api.${DOMAIN_NAME}"
      - "traefik.port=4444"
      - "traefik.docker.network=web"
    restart: on-failure
    ports:
      - "4444:4444"
    volumes:
      - "./config/:/config/"

  keto:
    container_name: keto
    image: oryd/keto:v0.2.2-sandbox_oryOS.10
    depends_on:
      - hydra_admin
      - hydra_public
      - keto-migrate
    links:
      - hydra_admin
      - hydra_public
      - postgresd
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra_public:4444/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra_admin:4445/oauth2/introspect
    networks:
      - intranet
    restart: on-failure
    volumes:
      - "./config/:/config/"

  ok-api:
    container_name: ok-api
    image: oryd/oathkeeper:v0.14.2_oryOS.10
    links:
      - hydra_admin
      - keto:keto
      - postgresd:postgresd
    networks:
      - intranet
      - web
    restart: on-failure
    environment:
      - LOG_LEVEL=debug
      - ISSUER_URL=http://ok-proxy:4455/
      - DATABASE_URL=postgres://${DB_USER}:${DB_PW}@postgresd:${DB_PORT}/${DB_NAME}?sslmode=disable
      - PORT=4456
      - CREDENTIALS_ISSUER_ID_TOKEN_HS256_SECRET=changemechangemechangemechangemedo
      - AUTHORIZER_KETO_URL=http://keto:4466
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra_admin:4445/oauth2/introspect
    command: serve api
    volumes:
      - "./config/:/config/"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=okapi"
      - "traefik.frontend.rule=Host:okapi.${DOMAIN_NAME}"
      - "traefik.port=4456"
      - "traefik.docker.network=web"

  ok-proxy:
    container_name: ok-proxy
    image: oryd/oathkeeper:v0.14.2_oryOS.10
    links:
      - hydra_admin
      - keto
      - ok-api
    restart: on-failure
    depends_on:
      - ok-api
    networks:
      - intranet
      - web
    volumes:
      - "./config/:/config/"
    environment:
      - LOG_LEVEL=debug
      - OATHKEEPER_API_URL=http://ok-api:4456
      - PORT=4455
      - CREDENTIALS_ISSUER_ID_TOKEN_HS256_SECRET=changemechangemechangemechangeme
      - AUTHORIZER_KETO_URL=http://keto:4466
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra_admin:4445/oauth2/introspect
    command: serve proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=okproxy"
      - "traefik.frontend.rule=Host:okproxy.${DOMAIN_NAME}"
      - "traefik.port=4455"
      - "traefik.docker.network=web"

  # minio:
  #   container_name: minio
  #   networks:
  #     - intranet
  #   image: minio/minio
  #   volumes:
  #     - "/Users/jorge/Desktop/minio:/data"
  #   ports:
  #     - 9000:9000
  #   command: server /data
  #   environment:
  #     - MINIO_ACCESS_KEY=piensa
  #     - MINIO_SECRET_KEY=puertico
  # mc:
  #   image: minio/mc
  #   networks:
  #     - intranet
  #   depends_on:
  #     - minio
  #   links:
  #     - minio:minio
  #   container_name: mc
  #   environment:
  #     - MINIO_ACCESS_KEY=piensa
  #     - MINIO_SECRET_KEY=puertico
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add res http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
  #     # /usr/bin/mc mb res/overall;
  #     /usr/bin/mc policy public res/overall;"

  # logico:
  #   container_name: logico
  #   image: ninjalikeme/logico
  #   command: /app/main
  #   networks:
  #     - intranet
  #     - web
  #   environment:
  #     - DB_USER=$DB_USER
  #     - DB_PW=$DB_PW
  #     - DB_NAME=$USER_DATABASE
  #     - DB_HOST=postgresd
  #     - DB_PORT=5432
  #     - HYDRA_BROWSER_URL=http://hydra_public:4444/oauth2/auth
  #     - HYDRA_PUBLIC_URL=http://hydra_public:4444/oauth2/token
  #     - HYDRA_ADMIN_URL=http://hydra_admin:4445
  #     # - HYDRA_CLIENT_ID=piensa
  #     # - HYDRA_CLIENT_SECRET=piensa
  #     # - HYDRA_SCOPES=openid,offline,eat,sleep,rave,repeat
  #     - PORT=3000
  #   links:
  #     - hydra_admin
  #     - hydra_public
  #     - postgresd
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=logico"
  #     - "traefik.frontend.rule=Host:logico.${DOMAIN_NAME}"
  #     - "traefik.port=3000"
  #     - "traefik.docker.network=web"

  postgresd:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - intranet
    volumes:
      - "./postgres/insert.sql:${DB_DUMP}"

  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./traefik.toml:/traefik.toml"
    command: --api --docker
    networks:
      - web

networks:
  web:
    external: true
  intranet:
    driver: bridge