debug = true
logLevel = "INFO"

defaultEntryPoints = ["http"]

[web]
# Port for the status/dashboard page
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = false
exposedByDefault = false